In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import numpy as np
import pandas as pd

# Load functional data

In [3]:
data_folder = "../data/preprocessed-data"

df_eyewire2_roi_level = pd.concat([pd.read_hdf(os.path.join(data_folder, f'df_eyewire2_roi_level_GCL{i}.h5'), key='dataframe') for i in range(5)])
df_eyewire2_field_level = pd.read_hdf(os.path.join(data_folder, 'df_eyewire2_field_level.h5'), key='dataframe')

In [4]:
print(df_eyewire2_roi_level.shape)
print(list(df_eyewire2_roi_level.columns))
df_eyewire2_roi_level.head()

(380, 53)
['experimenter', 'date', 'exp_num', 'raw_id', 'field', 'region', 'cond1', 'roi_id', 'chirp', 'cond2', 'preprocess_id', 'bar', 'mc', 'genline', 'animgender', 'eye', 'setupid', 'prepwmorient', 'nxpix', 'nypix', 'pixel_size_um', 'field_ventral_dorsal_pos_um', 'field_temporal_nasal_pos_um', 'roi_size_um2', 'roi_dia_um', 'ventral_dorsal_pos_um', 'temporal_nasal_pos_um', 'chirp_qidx', 'chirp_pres_qidx', 'chirp_average_norm', 'chirp_average_dt', 'chirp_snippets', 'chirp_snippets_t0', 'chirp_snippets_dt', 'chirp_triggertimes_snippets', 'bar_ds_index', 'bar_ds_pvalue', 'bar_pref_dir', 'bar_os_index', 'bar_os_pvalue', 'bar_pref_or', 'bar_qidx', 'bar_dir_component', 'bar_time_component', 'bar_pres_qidx', 'bar_snippets', 'bar_snippets_t0', 'bar_snippets_dt', 'bar_triggertimes_snippets', 'mc_trace', 'mc_trace_t0', 'mc_trace_dt', 'mc_triggertimes']

,experimenter,date,exp_num,raw_id,field,region,cond1,roi_id,chirp,cond2,...,bar_time_component,bar_pres_qidx,bar_snippets,bar_snippets_t0,bar_snippets_dt,bar_triggertimes_snippets,mc_trace,mc_trace_t0,mc_trace_dt,mc_triggertimes
0,Franke,2018-10-11,2,1,GCL0,RR,control,1,gChirp,control,...,"[0.093089096, -0.22815503, -0.1046858, -0.0340...",0.909091,"[[0.17414838, 1.9383364, 1.2062068, 0.31672782...","[15.876, 19.972, 23.94, 28.036, 32.004, 36.1, ...",0.128,"[[15.426, 19.464, 23.5, 27.538, 31.574, 35.612...","[1.2409285, 1.2420485, 1.5336616, 0.4615434, -...",0.004,0.128,"[16.126, 21.126, 26.13, 31.134, 36.14, 41.354,..."
1,Franke,2018-10-11,2,1,GCL0,RR,control,2,gChirp,control,...,"[-0.024774745, -0.017075807, 0.06123084, -0.06...",0.909091,"[[-0.5201849, -0.082454264, -0.061632738, -1.1...","[15.876, 19.972, 23.94, 28.036, 32.004, 36.1, ...",0.128,"[[15.426, 19.464, 23.5, 27.538, 31.574, 35.612...","[0.18298756, 0.18017985, 1.0832757, 1.8999918,...",0.004,0.128,"[16.126, 21.126, 26.13, 31.134, 36.14, 41.354,..."
2,Franke,2018-10-11,2,1,GCL0,RR,control,3,gChirp,control,...,"[0.07912462, 0.05823413, -0.021342145, 0.01906...",0.909091,"[[0.0, -0.15014112, 0.3378533, 0.18335032, 0.8...","[15.876, 19.972, 23.94, 28.036, 32.004, 36.1, ...",0.128,"[[15.426, 19.464, 23.5, 27.538, 31.574, 35.612...","[1.0008522, 1.0306789, 0.26217523, 2.5644557, ...",0.004,0.128,"[16.126, 21.126, 26.13, 31.134, 36.14, 41.354,..."
3,Franke,2018-10-11,2,1,GCL0,RR,control,4,gChirp,control,...,"[0.057342935, 0.034545735, 0.03877911, -0.0121...",0.909091,"[[0.0, -0.40650117, -0.4068029, 0.69550467, 1....","[15.876, 19.972, 23.94, 28.036, 32.004, 36.1, ...",0.128,"[[15.426, 19.464, 23.5, 27.538, 31.574, 35.612...","[2.7387435, 2.7615008, -0.08610359, -0.4735809...",0.004,0.128,"[16.126, 21.126, 26.13, 31.134, 36.14, 41.354,..."
4,Franke,2018-10-11,2,1,GCL0,RR,control,5,gChirp,control,...,"[0.055884045, 0.010200545, -0.011019, 0.001960...",0.909091,"[[0.0, 0.17036569, 0.5306051, 0.0, 0.0, 0.2800...","[15.876, 19.972, 23.94, 28.036, 32.004, 36.1, ...",0.128,"[[15.426, 19.464, 23.5, 27.538, 31.574, 35.612...","[2.667396, 2.6793451, 2.8424416, 2.65893, 2.20...",0.004,0.128,"[16.126, 21.126, 26.13, 31.134, 36.14, 41.354,..."

In [5]:
print(df_eyewire2_field_level.shape)
print(list(df_eyewire2_field_level.columns))
df_eyewire2_field_level.head()

(5, 22)
['experimenter', 'date', 'exp_num', 'raw_id', 'field', 'region', 'cond1', 'ch0_name', 'ch1_name', 'genline', 'animgender', 'eye', 'setupid', 'prepwmorient', 'nxpix', 'nypix', 'pixel_size_um', 'field_ventral_dorsal_pos_um', 'field_temporal_nasal_pos_um', 'ch0_average', 'ch1_average', 'roi_mask']

,experimenter,date,exp_num,raw_id,field,region,cond1,ch0_name,ch1_name,genline,...,setupid,prepwmorient,nxpix,nypix,pixel_size_um,field_ventral_dorsal_pos_um,field_temporal_nasal_pos_um,ch0_average,ch1_average,roi_mask
0,Franke,2018-10-11,2,1,GCL0,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-361.4,-841.8,"[[11019.5, 11015.0, 11022.0, 11064.0, 11099.0,...","[[10969.0, 10970.0, 10965.0, 10964.0, 10963.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
1,Franke,2018-10-11,2,1,GCL1,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-317.2,-761.4,"[[12043.0, 11088.0, 11062.0, 11028.0, 11037.0,...","[[10983.5, 10968.0, 10971.0, 10955.0, 10949.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
2,Franke,2018-10-11,2,1,GCL2,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-317.2,-985.4,"[[11937.0, 11062.0, 11219.0, 11164.0, 11034.0,...","[[10976.0, 10955.0, 10959.0, 10954.0, 10945.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
3,Franke,2018-10-11,2,1,GCL3,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-558.0,-935.2,"[[11037.0, 11081.0, 11081.0, 11079.0, 11052.0,...","[[10961.0, 16017.0, 16016.0, 15772.0, 14516.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
4,Franke,2018-10-11,2,1,GCL4,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-489.6,-622.2,"[[11002.0, 11050.0, 11056.0, 11040.0, 11033.0,...","[[10948.0, 10948.0, 10950.0, 10948.0, 10949.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."

# Load morphological data

TODO: update to latest spreadsheet and using mapping lookup-table.

In [6]:
morph_folder = "../data/morphological-data"
morph_spreadsheet_filename = "Eyewire II Proofreading - Calcium imaged cells - Proofreading 🧠.csv"

morph_df = pd.read_csv(os.path.join(os.path.join(morph_folder, morph_spreadsheet_filename)), header=3)

In [7]:
morph_df.shape

(380, 17)

In [8]:
print(list(morph_df.columns))

['Nuc Coords', 'Nuc ID', 'Soma Coords', 'OG Segment ID (Soma)', 'Segment ID (Soma, last update 202504110923)', 'Cell Type', 'EyeWire1 type (for RGCs)', 'Proofreader', 'Date Started', 'Temp Link', 'Status', 'Date Completed', 'Final Link', 'Final SegID', 'CA Imaged', 'Cell Class', 'Notes']

In [9]:
# Old spreadsheet for IDs only
id_spreadsheet_filename = "DO NOT USE - Ca imaged cells_Collaborators - overview.csv"
id_df = pd.read_csv(os.path.join(os.path.join(morph_folder, id_spreadsheet_filename)), header=0, skipfooter=37, engine='python')

In [10]:
id_df.shape

(380, 31)

In [11]:
print(list(id_df.columns))

['WIP (name)', 'Latest WIP view', 'Link to proofread cell with annotation', 'State (0=Red, 1=Yellow, 2=Green, 3=Proofread)', 'Cell number', 'experimenter', 'date', 'exp_num', 'raw_id', 'field', 'region', 'nucleus ID pcg', 'nucleus loc pcg', 'cell ID pcg', 'ID warning/error', 'Unnamed: 15', 'New IDs (last update: 202503260847)', 'roi_id', 'roi_n_pixels', 'roi_size_um2', 'super (baden)', 'group (baden)', 'cluster (baden)', 'cell type', 'RGC or AC', 'EyeWire 1 type (for RGCs)', 'most recent cell ID', 'field_ventral_dorsal_pos_um', 'field_temporal_nasal_pos_um', 'ventral_dorsal_pos_um', 'temporal_nasal_pos_um']

In [12]:
# Check that functional and morphological dataframes can be merged
assert (df_eyewire2_roi_level["date"].astype(str) == id_df["date"].astype(str)).all()
assert (df_eyewire2_roi_level["region"] == id_df["region"]).all()
assert (df_eyewire2_roi_level["field"] == id_df["field"]).all()
assert (df_eyewire2_roi_level["roi_id"].astype(str) == id_df["roi_id"].astype(str)).all()

for (i_new, row_new), (i_old, row_old) in zip(morph_df.iterrows(), id_df.iterrows()):
    xn, yn, zn = tuple(map(float, row_new['Nuc Coords'].split(',')))
    xo, yo, zo = tuple(map(float, row_old['nucleus loc pcg'].split(',')))

    assert np.allclose([xo, yo, zo], [xn, yn, zn])