In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import numpy as np
import pandas as pd

# Load functional data

In [4]:
from eyewire2_functional_analysis import data_loader

data_folder = "../data/preprocessed-data"

df_rois, df_fields, df_outline = data_loader.load_all_dfs(data_folder)

In [5]:
print(df_rois.shape)
print(list(df_rois.columns))
df_rois.head()

(379, 70)
['experimenter', 'date', 'exp_num', 'raw_id', 'field', 'region', 'cond1', 'ch0_name', 'ch1_name', 'roi_id', 'chirp', 'cond2', 'preprocess_id', 'bar', 'mc', 'chirp_stim_name', 'bar_stim_name', 'classifier_id', 'genline', 'animgender', 'eye', 'setupid', 'prepwmorient', 'nxpix', 'nypix', 'pixel_size_um', 'field_ventral_dorsal_pos_um', 'field_temporal_nasal_pos_um', 'ch0_average', 'ch1_average', 'roi_size_um2', 'roi_dia_um', 'ventral_dorsal_pos_um', 'temporal_nasal_pos_um', 'chirp_qidx', 'chirp_pres_qidx', 'chirp_average_norm', 'chirp_average_dt', 'chirp_snippets', 'chirp_snippets_t0', 'chirp_snippets_dt', 'chirp_triggertimes_snippets', 'bar_ds_index', 'bar_ds_pvalue', 'bar_pref_dir', 'bar_os_index', 'bar_os_pvalue', 'bar_pref_or', 'bar_qidx', 'bar_dir_component', 'bar_time_component', 'bar_pres_qidx', 'bar_snippets', 'bar_snippets_t0', 'bar_snippets_dt', 'bar_triggertimes_snippets', 'mc_trace', 'mc_trace_t0', 'mc_trace_dt', 'mc_triggertimes', 'cluster_id', 'group_id', 'supergroup', 'prob_cluster', 'prob_group', 'prob_supergroup', 'prob_class', 'probs_per_cluster', 'seg_id', 'nuc_id']

,experimenter,date,exp_num,raw_id,field,region,cond1,ch0_name,ch1_name,roi_id,...,cluster_id,group_id,supergroup,prob_cluster,prob_group,prob_supergroup,prob_class,probs_per_cluster,seg_id,nuc_id
0,Franke,2018-10-11,2,1,GCL0,RR,control,wDataCh0,wDataCh1,1,...,18,12,ON-OFF,0.804667,0.819760,0.832646,0.913740,"[0.0020822615335256726, 0.0032838992937911002,...",720575940550529705,720575940577751704
1,Franke,2018-10-11,2,1,GCL0,RR,control,wDataCh0,wDataCh1,2,...,51,34,dAC,0.605752,0.615440,0.702638,0.702638,"[0.003336756586838654, 0.008818983121221289, 0...",720575940568652126,720575940534317101
2,Franke,2018-10-11,2,1,GCL0,RR,control,wDataCh0,wDataCh1,3,...,68,42,dAC,0.772927,0.790771,0.927322,0.927322,"[0.0017071109567420337, 0.0016375104799094017,...",720575940572885792,720575940554891618
3,Franke,2018-10-11,2,1,GCL0,RR,control,wDataCh0,wDataCh1,4,...,74,46,dAC,0.488712,0.494132,0.803859,0.803859,"[0.0028589256378742686, 0.003341772704406851, ...",720575940566222700,720575940554657378
4,Franke,2018-10-11,2,1,GCL0,RR,control,wDataCh0,wDataCh1,5,...,38,28,Slow ON,0.580714,0.581366,0.590559,0.629739,"[0.0012246466912174362, 0.0011384551512382875,...",720575940577371948,720575940571117757

In [6]:
print(df_fields.shape)
print(list(df_fields.columns))
df_fields.head()

(5, 22)
['experimenter', 'date', 'exp_num', 'raw_id', 'field', 'region', 'cond1', 'ch0_name', 'ch1_name', 'genline', 'animgender', 'eye', 'setupid', 'prepwmorient', 'nxpix', 'nypix', 'pixel_size_um', 'field_ventral_dorsal_pos_um', 'field_temporal_nasal_pos_um', 'ch0_average', 'ch1_average', 'roi_mask']

,experimenter,date,exp_num,raw_id,field,region,cond1,ch0_name,ch1_name,genline,...,setupid,prepwmorient,nxpix,nypix,pixel_size_um,field_ventral_dorsal_pos_um,field_temporal_nasal_pos_um,ch0_average,ch1_average,roi_mask
0,Franke,2018-10-11,2,1,GCL0,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-361.4,-841.8,"[[11019.5, 11015.0, 11022.0, 11064.0, 11099.0,...","[[10969.0, 10970.0, 10965.0, 10964.0, 10963.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
1,Franke,2018-10-11,2,1,GCL1,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-317.2,-761.4,"[[12043.0, 11088.0, 11062.0, 11028.0, 11037.0,...","[[10983.5, 10968.0, 10971.0, 10955.0, 10949.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
2,Franke,2018-10-11,2,1,GCL2,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-317.2,-985.4,"[[11937.0, 11062.0, 11219.0, 11164.0, 11034.0,...","[[10976.0, 10955.0, 10959.0, 10954.0, 10945.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
3,Franke,2018-10-11,2,1,GCL3,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-558.0,-935.2,"[[11037.0, 11081.0, 11081.0, 11079.0, 11052.0,...","[[10961.0, 16017.0, 16016.0, 15772.0, 14516.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."
4,Franke,2018-10-11,2,1,GCL4,RR,control,wDataCh0,wDataCh1,Bl6,...,3,180,64,64,1.46998,-489.6,-622.2,"[[11002.0, 11050.0, 11056.0, 11040.0, 11033.0,...","[[10948.0, 10948.0, 10950.0, 10948.0, 10949.0,...","[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,..."

# Load morphological data

TODO: update to latest spreadsheet and using mapping lookup-table.

In [7]:
morph_folder = "../data/morphological-data"
morph_spreadsheet_filename = "Eyewire II Proofreading - Calcium imaged cells - Proofreading 🧠.csv"

morph_df = pd.read_csv(os.path.join(os.path.join(morph_folder, morph_spreadsheet_filename)), header=3)

In [7]:
morph_df.shape

(380, 17)

In [8]:
print(list(morph_df.columns))

['Nuc Coords', 'Nuc ID', 'Soma Coords', 'OG Segment ID (Soma)', 'Segment ID (Soma, last update 202504110923)', 'Cell Type', 'EyeWire1 type (for RGCs)', 'Proofreader', 'Date Started', 'Temp Link', 'Status', 'Date Completed', 'Final Link', 'Final SegID', 'CA Imaged', 'Cell Class', 'Notes']

In [9]:
# Old spreadsheet for IDs only
id_spreadsheet_filename = "DO NOT USE - Ca imaged cells_Collaborators - overview.csv"
id_df = pd.read_csv(os.path.join(os.path.join(morph_folder, id_spreadsheet_filename)), header=0, skipfooter=37, engine='python')

In [10]:
id_df.shape

(380, 31)

In [11]:
print(list(id_df.columns))

['WIP (name)', 'Latest WIP view', 'Link to proofread cell with annotation', 'State (0=Red, 1=Yellow, 2=Green, 3=Proofread)', 'Cell number', 'experimenter', 'date', 'exp_num', 'raw_id', 'field', 'region', 'nucleus ID pcg', 'nucleus loc pcg', 'cell ID pcg', 'ID warning/error', 'Unnamed: 15', 'New IDs (last update: 202503260847)', 'roi_id', 'roi_n_pixels', 'roi_size_um2', 'super (baden)', 'group (baden)', 'cluster (baden)', 'cell type', 'RGC or AC', 'EyeWire 1 type (for RGCs)', 'most recent cell ID', 'field_ventral_dorsal_pos_um', 'field_temporal_nasal_pos_um', 'ventral_dorsal_pos_um', 'temporal_nasal_pos_um']

In [12]:
# Check that functional and morphological dataframes can be merged
assert (df_rois["date"].astype(str) == id_df["date"].astype(str)).all()
assert (df_rois["region"] == id_df["region"]).all()
assert (df_rois["field"] == id_df["field"]).all()
assert (df_rois["roi_id"].astype(str) == id_df["roi_id"].astype(str)).all()

for (i_new, row_new), (i_old, row_old) in zip(morph_df.iterrows(), id_df.iterrows()):
    xn, yn, zn = tuple(map(float, row_new['Nuc Coords'].split(',')))
    xo, yo, zo = tuple(map(float, row_old['nucleus loc pcg'].split(',')))

    assert np.allclose([xo, yo, zo], [xn, yn, zn])