# Imports

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
from matplotlib import pyplot as plt
import pandas as pd
from IPython.core.display_functions import clear_output

# Load data

In [3]:
data_folder = "../../data/preprocessed-data"
df_eyewire2_field_level = pd.read_hdf(os.path.join(data_folder, 'df_fields.h5'), key='dataframe')

In [4]:
df_eyewire2_roi_level = pd.concat([pd.read_hdf(os.path.join(data_folder, f'df_eyewire2_roi_level_GCL{i}.h5'), key='dataframe') for i in range(5)])
df_eyewire2_roi_level['date'] = df_eyewire2_roi_level['date'].astype(str)
df_eyewire2_roi_level['exp_num'] = 2
df_eyewire2_roi_level['roi_id'] = df_eyewire2_roi_level['roi_id'].astype(int)
df_eyewire2_roi_level = df_eyewire2_roi_level.set_index(['date', 'exp_num', 'field', 'roi_id'])
df_eyewire2_roi_level.head()

                                experimenter  raw_id region    cond1  \
date       exp_num field roi_id
2018-10-11 2       GCL0  1            Franke       1     RR  control
                         2            Franke       1     RR  control
                         3            Franke       1     RR  control
                         4            Franke       1     RR  control
                         5            Franke       1     RR  control

                                 ch0_name  ch1_name   chirp    cond2  \
date       exp_num field roi_id
2018-10-11 2       GCL0  1       wDataCh0  wDataCh1  gChirp  control
                         2       wDataCh0  wDataCh1  gChirp  control
                         3       wDataCh0  wDataCh1  gChirp  control
                         4       wDataCh0  wDataCh1  gChirp  control
                         5       wDataCh0  wDataCh1  gChirp  control

                                 preprocess_id        bar  ... mc_trace_dt  \
date       exp_num field roi_id                            ...
2018-10-11 2       GCL0  1                   1  movingbar  ...       0.128
                         2                   1  movingbar  ...       0.128
                         3                   1  movingbar  ...       0.128
                         4                   1  movingbar  ...       0.128
                         5                   1  movingbar  ...       0.128

                                                                   mc_triggertimes  \
date       exp_num field roi_id
2018-10-11 2       GCL0  1       [16.126, 21.126, 26.13, 31.134, 36.14, 41.354,...
                         2       [16.126, 21.126, 26.13, 31.134, 36.14, 41.354,...
                         3       [16.126, 21.126, 26.13, 31.134, 36.14, 41.354,...
                         4       [16.126, 21.126, 26.13, 31.134, 36.14, 41.354,...
                         5       [16.126, 21.126, 26.13, 31.134, 36.14, 41.354,...

                                cluster_id  group_id supergroup prob_cluster  \
date       exp_num field roi_id
2018-10-11 2       GCL0  1              18        12     ON-OFF     0.804667
                         2              51        34        dAC     0.605752
                         3              68        42        dAC     0.772927
                         4              74        46        dAC     0.488712
                         5              38        28    Slow ON     0.580714

                                prob_group prob_supergroup  prob_class  \
date       exp_num field roi_id
2018-10-11 2       GCL0  1        0.819760        0.832646    0.913740
                         2        0.615440        0.702638    0.702638
                         3        0.790771        0.927322    0.927322
                         4        0.494132        0.803859    0.803859
                         5        0.581366        0.590559    0.629739

                                                                 probs_per_cluster
date       exp_num field roi_id
2018-10-11 2       GCL0  1       [0.0020822615335256726, 0.0032838992937911002,...
                         2       [0.003336756586838654, 0.008818983121221289, 0...
                         3       [0.0017071109567420337, 0.0016375104799094017,...
                         4       [0.0028589256378742686, 0.003341772704406851, ...
                         5       [0.0012246466912174362, 0.0011384551512382875,...

[5 rows x 64 columns]

In [5]:
morph_folder = "../../data/morphological-data"
morph_spreadsheet_filename = "Eyewire II Proofread Cells Master List - All Cells (WIP) 2025-09-03.csv"

morph_df = pd.read_csv(os.path.join(os.path.join(morph_folder, morph_spreadsheet_filename)), dtype=str)
print(morph_df.shape)
morph_df.head()

(8893, 41)

,Index,Nuc Coords,Soma Coords,Cell Type (deprecated),611 Proofreader,Proofreader 2,Status,AIS annotated?,Final Link,Final NucID,...,Index for sanity check,Index ok?,updated?,Index OK?,Index for sanity check.1,Updated Nuc ID (Sept 2),Updated Seg ID (Sept 2),Cell Requires Review (DO NOT use Updated IDs for those cells),Review complete,Review notes
0,A4,NaN,NaN,OFF-SAC,Roden Rey,NaN,Complete (cut off),NaN,https://spelunker.cave-explorer.org/#!middleau...,NaN,...,A4,ok,no soma coords,ok,A4,NaN,NaN,FALSE,NaN,NaN
1,A5,NaN,NaN,OFF-SAC,Christine,NaN,Complete (cut off),NaN,https://spelunker.cave-explorer.org/#!middleau...,NaN,...,A5,ok,no soma coords,ok,A5,NaN,NaN,FALSE,NaN,NaN
2,A6,"35877, 25970, 1747","35799, 26155, 1578",OFF-SAC,Christine,NaN,Complete,NaN,https://spelunker.cave-explorer.org/#!middleau...,720575940555518380,...,A6,ok,UPDATED,ok,A6,720575940555518380,720575940556408295,FALSE,NaN,NaN
3,A7,"63573, 49070, 1720","63537, 49048, 1697",OFF-SAC,April Grace,NaN,Complete,NaN,https://spelunker.cave-explorer.org/#!middleau...,720575940545056597,...,A7,ok,same,ok,A7,720575940545056597,720575940572159335,FALSE,NaN,NaN
4,A11,"50561, 64354, 1734","50520, 64370, 1656",OFF-SAC,Roden Rey,NaN,Complete,NaN,https://spelunker.cave-explorer.org/#!middleau...,720575940544186175,...,A11,ok,same,ok,A11,720575940544186175,720575940563309953,FALSE,NaN,NaN

In [6]:
mapping_spreadsheet_filename = "roi_mapping_2p_to_em.csv"

mapping_df = pd.read_csv(os.path.join(os.path.join(morph_folder, mapping_spreadsheet_filename)), dtype=str)
mapping_df['exp_num'] = 2
mapping_df['roi_id'] = mapping_df['roi_id'].astype(int)
mapping_df = mapping_df.set_index(['date', 'exp_num', 'field', 'roi_id'])
print(mapping_df.shape)
mapping_df.head()

(380, 2)

                                Updated Seg ID (Sept 2)  \
date       exp_num field roi_id
2018-10-11 2       GCL0  1           720575940550529705
                         2           720575940568652126
                         3           720575940572885792
                         4           720575940566222700
                         5           720575940577371948

                                Updated Nuc ID (Sept 2)
date       exp_num field roi_id
2018-10-11 2       GCL0  1           720575940577751704
                         2           720575940534317101
                         3           720575940554891618
                         4           720575940554657378
                         5           720575940571117757

In [7]:
nuc_col = 'Updated Nuc ID (Sept 2)'

assert nuc_col in morph_df.columns, f"Column '{nuc_col}' not found in morph_df"
assert nuc_col in mapping_df.columns, f"Column '{nuc_col}' not found in mapping_df"

df = df_eyewire2_roi_level.join(mapping_df)
df = df.reset_index().set_index(nuc_col)

morph_df_ = morph_df[morph_df[nuc_col].notna()].set_index(nuc_col)
morph_df_ = morph_df_[~morph_df_.index.duplicated(keep='first')]
df = pd.merge(df, morph_df_, left_index=True, right_index=True, how='inner').reset_index()
df['qfilt'] = (df['bar_qidx'] > 0.6) | (df['chirp_qidx'] > 0.45)

print(list(df.columns))
print(df.shape)
df.head()

['Updated Nuc ID (Sept 2)', 'date', 'exp_num', 'field', 'roi_id', 'experimenter', 'raw_id', 'region', 'cond1', 'ch0_name', 'ch1_name', 'chirp', 'cond2', 'preprocess_id', 'bar', 'mc', 'chirp_stim_name', 'bar_stim_name', 'classifier_id', 'genline', 'animgender', 'eye', 'setupid', 'prepwmorient', 'nxpix', 'nypix', 'pixel_size_um', 'field_ventral_dorsal_pos_um', 'field_temporal_nasal_pos_um', 'ch0_average', 'ch1_average', 'roi_size_um2', 'roi_dia_um', 'ventral_dorsal_pos_um', 'temporal_nasal_pos_um', 'chirp_qidx', 'chirp_pres_qidx', 'chirp_average_norm', 'chirp_average_dt', 'chirp_snippets', 'chirp_snippets_t0', 'chirp_snippets_dt', 'chirp_triggertimes_snippets', 'bar_ds_index', 'bar_ds_pvalue', 'bar_pref_dir', 'bar_os_index', 'bar_os_pvalue', 'bar_pref_or', 'bar_qidx', 'bar_dir_component', 'bar_time_component', 'bar_pres_qidx', 'bar_snippets', 'bar_snippets_t0', 'bar_snippets_dt', 'bar_triggertimes_snippets', 'mc_trace', 'mc_trace_t0', 'mc_trace_dt', 'mc_triggertimes', 'cluster_id', 'group_id', 'supergroup', 'prob_cluster', 'prob_group', 'prob_supergroup', 'prob_class', 'probs_per_cluster', 'Updated Seg ID (Sept 2)_x', 'Index', 'Nuc Coords', 'Soma Coords', 'Cell Type (deprecated)', '611 Proofreader', 'Proofreader 2', 'Status', 'AIS annotated?', 'Final Link', 'Final NucID', 'Final SegID', 'Directionality', 'Proofreading Notes', 'Status (Julia)', 'Notes (Julia)', 'Cell Class', 'Cell Typer Name', 'Cell Type', 'Reliability Human Label', 'Other Type', 'EyeWire1 type (for RGCs) human label', 'Reliability EyeWire1 human label', 'Labeling Notes', 'Machine label', 'Confidence machine label', 'Machine soma location', 'Status (Julia/Sebastian)', 'Additional Notes', 'Updated Seg IDs (July 25)', 'Most recent SegID (2025-08-26)', 'Seg ID auto merge', 'Index for sanity check', 'Index ok?', 'updated?', 'Index OK?', 'Index for sanity check.1', 'Updated Seg ID (Sept 2)_y', 'Cell Requires Review (DO NOT use Updated IDs for those cells)', 'Review complete', 'Review notes', 'qfilt']
(380, 111)

,Updated Nuc ID (Sept 2),date,exp_num,field,roi_id,experimenter,raw_id,region,cond1,ch0_name,...,Index for sanity check,Index ok?,updated?,Index OK?,Index for sanity check.1,Updated Seg ID (Sept 2)_y,Cell Requires Review (DO NOT use Updated IDs for those cells),Review complete,Review notes,qfilt
0,720575940577751704,2018-10-11,2,GCL0,1,Franke,1,RR,control,wDataCh0,...,D1,ok,UPDATED,ok,D1,720575940550529705,FALSE,NaN,NaN,False
1,720575940534317101,2018-10-11,2,GCL0,2,Franke,1,RR,control,wDataCh0,...,D2,ok,same,ok,D2,720575940568652126,FALSE,NaN,NaN,True
2,720575940554891618,2018-10-11,2,GCL0,3,Franke,1,RR,control,wDataCh0,...,B94,ok,same,ok,B94,720575940572885792,FALSE,NaN,NaN,True
3,720575940554657378,2018-10-11,2,GCL0,4,Franke,1,RR,control,wDataCh0,...,D4,ok,UPDATED,ok,D4,720575940566222700,FALSE,NaN,NaN,True
4,720575940571117757,2018-10-11,2,GCL0,5,Franke,1,RR,control,wDataCh0,...,D5,ok,same,ok,D5,720575940577371948,FALSE,NaN,NaN,True

# Plot data

In [8]:
from eyewire2_functional_analysis.plot_dataframe import plot_df_chirp_and_bar

In [11]:
fig_dir = './figures/responses_by_field'
os.makedirs(fig_dir, exist_ok=True)

for (field, cell_class), df_plot in df.groupby(['field', 'Cell Class']):
    clear_output()
    fig, axs = plot_df_chirp_and_bar(df=df_plot, id_col=nuc_col, type_col='Cell Type',
                                     title=f"{field}: All {cell_class}s", chirp_q_thresh=0.45, bar_q_thresh=0.6)
    plt.savefig(os.path.join(fig_dir, f'response_overview_{field}_{cell_class}.pdf'))
    plt.close(fig)

In [13]:
fig_dir = './figures/responses_by_type'
os.makedirs(fig_dir, exist_ok=True)

def simplify_cell_type(cell_type_):
    # Return None if the cell type is None or NaN
    if cell_type_ is None or pd.isna(cell_type_):
        return None

    # Convert to string in case it's not already
    cell_type_ = str(cell_type_)

    # Remove question marks
    cell_type_ = cell_type_.replace('?', '')

    # Remove expressions of uncertainty
    uncertainty_phrases = ['maybe', 'I think', 'probably', 'or', '-ish']
    for phrase in uncertainty_phrases:
        # Split by phrase and take the first part
        if phrase in cell_type_.lower():
            parts = cell_type_.lower().split(phrase)
            cell_type_ = parts[0].strip()

    # If the cell type became empty after cleaning, return None
    if not cell_type_ or cell_type_.isspace():
        return None

    # Return the cleaned cell type
    return cell_type_.strip()

df['Cell Type simplified'] = df['Cell Type'].apply(simplify_cell_type)

for cell_type, df_plot in df.groupby('Cell Type simplified'):
    clear_output()
    fig, axs = plot_df_chirp_and_bar(
        df=df_plot.sort_values(['field', 'roi_id'], inplace=False),
        id_col=nuc_col, type_col='Cell Type',
        title=cell_type, chirp_q_thresh=0.45, bar_q_thresh=0.6)
    plt.savefig(os.path.join(fig_dir, f'response_overview_{cell_type}.pdf'))
    plt.close(fig)